### ISSUE TITLE
Makefile:100: recipe for target 'all' failed

### ISSUE THREAD

**Issue by kapoormanav** [PalamaraLab/FastSMC#5] opened 2021-09-01 19:40 UTC
I am not able to compile the FastSMC. I am getting following error/s. It would be great if you can help me to resolve the issue.

```
[  3%] Building CXX object CMakeFiles/ASMC.dir/ASMC_SRC/SRC/HMM.cpp.o
In file included from /software/FastSMC/ASMC_SRC/SRC/HMM.hpp:20:0,
                 from /software/FastSMC/ASMC_SRC/SRC/HMM.cpp:16:
/software/FastSMC/ASMC_SRC/SRC/DecodePairsReturnStruct.hpp:19:0: warning: ignoring #pragma clang diagnostic [-Wunknown-pragmas]
 #pragma clang diagnostic push
 
/software/FastSMC/ASMC_SRC/SRC/DecodePairsReturnStruct.hpp:20:0: warning: ignoring #pragma ide diagnostic [-Wunknown-pragmas]
 #pragma ide diagnostic ignored "cppcoreguidelines-non-private-member-variables-in-classes"
 
In file included from /software/FastSMC/ASMC_SRC/SRC/HMM.hpp:20:0,
                 from /software/FastSMC/ASMC_SRC/SRC/HMM.cpp:16:
/software/FastSMC/ASMC_SRC/SRC/DecodePairsReturnStruct.hpp:128:0: warning: ignoring #pragma clang diagnostic [-Wunknown-pragmas]
 #pragma clang diagnostic pop
 
/software/FastSMC/ASMC_SRC/SRC/HMM.cpp:21:10: fatal error: filesystem: No such file or directory
 #include <filesystem>
          ^~~~~~~~~~~~
compilation terminated.
CMakeFiles/ASMC.dir/build.make:75: recipe for target 'CMakeFiles/ASMC.dir/ASMC_SRC/SRC/HMM.cpp.o' failed
make[2]: *** [CMakeFiles/ASMC.dir/ASMC_SRC/SRC/HMM.cpp.o] Error 1
CMakeFiles/Makefile2:118: recipe for target 'CMakeFiles/ASMC.dir/all' failed
make[1]: *** [CMakeFiles/ASMC.dir/all] Error 2
Makefile:100: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by fcooper8472** [comment] 2021-09-01 21:27
Hi @kapoormanav,

It looks as though your compiler does not support [`std::filesystem`](https://en.cppreference.com/w/cpp/header/filesystem).

I can't tell from that snippet exactly what compiler you're using, but I would recommend GCC 8.3+, Clang 7+ or AppleClang 11.0+.

In addition, this repository will soon be marked as deprecated as the functionality is being relocated and enhanced [here](https://github.com/PalamaraLab/ASMC). 
I recommend using this new repository, which contains all the same functionality.
Please see this [quickstart guide](https://github.com/PalamaraLab/ASMC/blob/main/docs/quickstart_user.md) for instructions on compiling the software, although please note that the python wheels are not yet available on PyPI.

Let me know if either suggestion solves the problem you're having.

**Comment by kapoormanav** [comment] 2021-09-02 03:04
Hi @fcooper8472 

Thanks for the suggestions. I updated GCC 8.3+ and Clang 7+ and it still gave error.

But good news is that the install worked for the new repository and finished without error. 

Thanks,

-Manav

**Comment by fcooper8472** [comment] 2021-09-02 10:51
Hi @kapoormanav,

Thanks for investigating further and glad it's working on the new repository.

It would be great to fix this issue in any case... if you have a minute could you possibly re-run the CMake step from a clean build directory and copy the full output from CMake into this issue?

Thanks

**Comment by kapoormanav** [comment] 2021-09-02 14:02
Hi @fcooper8472 

Here is the error message that I am getting during the build.

Thanks,

`[  3%] Building CXX object CMakeFiles/ASMC.dir/ASMC_SRC/SRC/HmmUtils.cpp.o
In file included from /home/s.manav.kapoor/FastSMC/ASMC_SRC/SRC/HmmUtils.cpp:26:
/usr/include/fmt/format.h: In instantiation of ‘void fmt::internal::format_arg(Formatter&, const Char*, const T&) [with Formatter = fmt::BasicFormatter<char>; Char = char; T = std::basic_string_view<char>]’:
/usr/include/fmt/format.h:1302:15:   required from ‘static void fmt::internal::MakeValue<Formatter>::format_custom_arg(void*, const void*, void*) [with T = std::basic_string_view<char>; Formatter = fmt::BasicFormatter<char>]’
/usr/include/fmt/format.h:1395:19:   required from ‘fmt::internal::MakeValue<Formatter>::MakeValue(const T&, typename fmt::internal::EnableIf<fmt::internal::Not<fmt::internal::ConvertToInt<T>::value>::value, int>::type) [with T = std::basic_string_view<char>; Formatter = fmt::BasicFormatter<char>; typename fmt::internal::EnableIf<fmt::internal::Not<fmt::internal::ConvertToInt<T>::value>::value, int>::type = int]’
/usr/include/fmt/format.h:2234:12:   required from ‘static fmt::internal::Value fmt::internal::ArgArray<N, true>::make(const T&) [with Formatter = fmt::BasicFormatter<char>; T = std::basic_string_view<char>; long unsigned int N = 2]’
/usr/include/fmt/format.h:3586:1:   required from ‘std::string fmt::format(fmt::CStringRef, const Args& ...) [with Args = {std::basic_string_view<char, std::char_traits<char> >, long unsigned int}; std::string = std::__cxx11::basic_string<char>; fmt::CStringRef = fmt::BasicCStringRef<char>]’
/home/s.manav.kapoor/FastSMC/ASMC_SRC/SRC/HmmUtils.cpp:194:99:   required from here
/usr/include/fmt/format.h:1253:3: error: static assertion failed: Cannot format argument. To enable the use of ostream operator<< include fmt/ostream.h. Otherwise provide an overload of format_arg.
 1253 |   FMT_STATIC_ASSERT(FalseType<T>::value,
      |   ^~~~~~~~~~~~~~~~~
CMakeFiles/ASMC.dir/build.make:89: recipe for target 'CMakeFiles/ASMC.dir/ASMC_SRC/SRC/HmmUtils.cpp.o' failed
make[2]: *** [CMakeFiles/ASMC.dir/ASMC_SRC/SRC/HmmUtils.cpp.o] Error 1
CMakeFiles/Makefile2:222: recipe for target 'CMakeFiles/ASMC.dir/all' failed
make[1]: *** [CMakeFiles/ASMC.dir/all] Error 2
Makefile:100: recipe for target 'all' failed
make: *** [all] Error 2`

**Comment by fcooper8472** [comment] 2021-09-02 14:30
Hi @kapoormanav,

Unfortunately I can't reproduce that error locally.  Without the CMake output from a clean build I won't be able to investigate this any further.

Thanks,

**Comment by kapoormanav** [comment] 2021-09-02 15:23
Hi @fcooper8472 ,

This is the output from Cmake. Please let me know if this output you need.

Thanks,

`-- CMake version: 3.21.1
-- The CXX compiler identification is GNU 9.4.0
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Setting build type to 'Release' as none was specified.
--   You can specify with the flag -DCMAKE_BUILD_TYPE=<Debug|Release|MinSizeRel|RelWithDebInfo>
--   'Release' will build optimised binaries, but 'Debug' may be better while developing FastSMC.
-- CMake build type is set to Release
-- AVX instruction set
-- Found Boost: /usr/include (found version "1.65.1") found components: program_options iostreams regex 
-- Found ZLIB: /usr/lib/x86_64-linux-gnu/libz.so (found version "1.2.11") 
-- Found OpenMP_CXX: -fopenmp (found version "4.5") 
-- Found OpenMP: TRUE (found version "4.5")  
-- Configuring done
-- Generating done
-- Build files have been written to: /home/s.manav.kapoor/FastSMC/FASTSMC_BUILD_DIR`

**Comment by fcooper8472** [comment] 2021-09-02 16:00
Thanks @kapoormanav, yes, that's what I needed.

I believe the problem is you have an old version of [the {fmt} library](https://fmt.dev/latest/index.html).  The installation instructions were out of date and did not include the instruction to recursively clone submodules, which would have installed a suitable version for you during the CMake step.

Please could you try again with the latest version of this repository?  The slightly updated instructions can now be found here:
https://github.com/PalamaraLab/FastSMC/blob/master/LEGACY_README.md

Thanks,

**Comment by kapoormanav** [comment] 2021-09-02 19:01
Thanks a lot @fcooper8472 , the installation worked from the updated instructions!

**Comment by fcooper8472** [comment] 2021-09-02 19:03
Perfect, thanks very much for helping track this down.

**Closed by fcooper8472** 2021-09-02 19:03 UTC
